add likes and friends functionally
Sem4es14/java-filmorate pull request #5
Opened 2022-08-25 20:37 UTC by Sem4es14

2022-08-27 19:59 UTC, sergeymamonov requested changes

2022-08-27 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/fillmorate/storage/film/InMemoryFilmStorage.java
> +        films.put(film.getId(), film);
А если в мапе уже будет объект с таким же id? Лучше сделать такую проверку. В статусах Http ответов это будет 409 код, а значит обработку такой ошибки нужно будет добавить в обработчик.

2022-08-27 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/fillmorate/storage/film/InMemoryFilmStorage.java
> +        return "OK";
Обычно так не делают. Можно вернуть сам удаляемый объект, можно ничего не возвращать, можно вернуть id удаленного объекта. Но просто строку это бесполезно. Тут лучше подумать над возвращаемым значением, потому что этот метод в интерфейсе, а их править не просто, так как потом ими будут пользоваться клиенты. И придется поднимать версию интрефейса, поддерживать два и более интерфейса и так далее, поэтому интерфейс нужно тщательно продумывать.

А если удаляемого объекта не будет в мапе, метод вернет опять же OK, верно ли это?

2022-08-27 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/fillmorate/service/film/FilmService.java
>          Film film = Film.builder()
Если захотите, посмотрите про Mapstruct, чтобы не делать таких билдеров, можно использовать маппер. Но это по желанию, не настаиваю на его использовании.

2022-08-29 10:59 UTC, Sem4es14 commented on src/main/java/ru/yandex/practicum/fillmorate/storage/film/InMemoryFilmStorage.java
> +        films.put(film.getId(), film);
Перед добавлением фильма в мапу, ему каждый раз присваивается уникальный id, поэтому в мапе не может лежать фильм с таким же id. При вызове метода update мы изменяет объект который опять же достали из мапы, поэтому случайно записать id вручную не получится. Значит в мапе просто не может оказаться объект с id который хранилище устанавливает при добавлении в мапу. 
Но если предположить, что это произошло, почему 409 ошибка? Клиент присылает фильм без id, значит клиент не может быть причастен к тому что фильм с таким id уже существует в базе. Тогда это скорее 500 ошибка должна быть. Разве не так?

2022-08-29 20:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/fillmorate/storage/film/InMemoryFilmStorage.java
> +        films.put(film.getId(), film);
Лучше стараться не возвращать 500 ошибку клиенту. Всегда стараются вернуть 4хх ошибку. Во-первых, эта ошибка информативна, она дает понять, что произошло. Во-вторых, это какая-то обрабатываемая ошибка, то есть при написании программы мы продумали, что такая ситуация может возникнуть. 
Если бы код всегда работал так, как мы хотим, то багов в проде и у клиентов не было. Самый простой пример, вдруг потом решат сделать приложение многопоточным, и внесут не все нужные  изменения и проверки. И когда два потока будут писать в мапу с одинаковым id, то один поток перезатрет результат первого потока. 
В корректно работающем приложении проверка не записано ли id уже в мапу будет всегда давать отрицательный результат, но мой совет, лучше сделать такую проверку. Вообще любые получаемые данные лучше проверять.

2022-08-29 20:52 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/fillmorate/service/film/FilmService.java
> +        film.getLikes().add(user.getId());
Посмотрите, что возвращают методы add, remove. Результатами работы этих методов при желании можно воспользоваться.

2022-08-29 20:52 UTC, sergeymamonov approved these changes

2022-09-25 15:56 UTC, merged